### ISSUE TITLE
Improve filter slider

### ISSUE THREAD

**Issue by dzannotti** [dzannotti/junox#1]
I need to find a better formula (more realistic) for slider to frequency.

https://github.com/pendragon-andyh/Juno60 has lots of samples, perhaps @pendragon-andyh already has this figured out?

**Comment by pendragon-andyh** [comment]
Can you point me to where your current formula is?

From the Juno-106 service manual (which you can download as PDF from various places on the web):
Cutoff Freq: 5Hz to 50KHz
Env Mod: +/-14 octaves
LFO mod: +/-3.5 octaves
Bender: +-3.5 octaves
Key follow: +3/-2 octaves

On pages 18/19 there is some stuff for adjusting the Juno's internal stuff.  That might give some pointers.

Just off to dinner now.  If I get time later then I will see if I can get some more clues.

**Comment by dzannotti** [comment]
@pendragon-andyh thank you so much for weighting in on this!!!
The formula I'm referring to is slider (0..1) to frequency (again normalized between 0 and 1 - where 1 is nyquist freq 22050Hz)

it's here https://github.com/dzannotti/junox/blob/master/src/junox/params.js#L45
here's how the filter current value is calculated (patch is the slider value between 0 and 1), 
https://github.com/dzannotti/junox/blob/master/src/junox/voice.js#L65

I did consult the manual, but i strongly suspect those sliders aren't of linear output. While testing against original patches i noticed that a linear slider to frequency didn't result in much similarity while an exponential one made the synth bass I match quite decently.

I'm not sure I fully understand env mod being +- 14 Octaves in the vcf, can you please elaborate over that?

**Comment by pendragon-andyh** [comment]
I agree, there is absolutely nothing linear in the entire synth.  When synths were fully analogue, it was common to see "1 volt per octave".  Taking the Juno's LFO modulation as an example, you would multiple the LFO's so that its peek-to-peek range is (depending on the slider) up to +-3.5 volts, then feed that into the VCF's cutoff-frequency.

When I was previously trying to implement the Juno, I was going to try the following:
* Set the filter's frequency to 5 Hz.
* Drive the filter's Detune parameter from the slider (if the slider's range is 0-1) multiple the slider's value by 29.5*1400 before poking it into the Detune parameter.  This gives you 5Hz to 50KHz (taken from the service notes specification).
* Take the LFO's output (range = -1 to +1) and multiply that by 3.5*1400 before connecting that to the Detune.
* Take the ADSR's output, if "Invert" is set then multiple by -1, then multiply by 14*1400 before connecting to the Detune.
* Take the pitch-bend (-1 to 1), multiple that by the "VCF bend-sensitivity" (to the left of the keyboard) slider (0-1), then multiply by 3.5*1400 before connecting that to the Detune.
* Take the key-follow slider (0-1), subtract 0.4, then multiply by 5*1400 before connecting to the Detune.

My assumption is that the filter will ignore any frequency that is above 22050Hz.

Separate note: I saw a reference to "chorusModeToFeedback" in params.js.  There is no feedback in the chorus circuit.  The analysis of this in my "Juno60" repo is pretty-much complete.

**Comment by dzannotti** [comment]
@pendragon-andyh thank you so much! Feel free to ignore my help requests btw, i might eventually figure this things out myself. I just seen all your beautiful analysis and couldn't help but reference it here, and this whole thing wouldn't even exist without your repo to start with.

Wouldn't `sliderValue * 29.5 * 1400` still be a linear relationship between the slider value and the actual cutoff frequency in Hz? I think that slider does not linearly map to the cutoff frequency (I should really use your wav files thru a spectrum analiser to figure out some fudge/exponential values, i was just wondering if you already figured that part out)

The LFO mod/env mod and Key Follow suggestions are great!!. I'm definitely going to implement them in!

wrt to the chorus, thank you!

separate note: since you own/owned a juno and after playing with the web version, how far off am i? I imagine quite a large margin

**Comment by dzannotti** [comment]
Ultimately i'm trying to understand the relationship between the VCF Frequency slider and the actual cutoff frequency. I do believe that part is missing from your analysis https://github.com/pendragon-andyh/Juno60/tree/master/Filter/VCF

**Comment by pendragon-andyh** [comment]
Whoops! Replace 1400 with 1200!  The 29.5 is wrong also.  Try 13.2877.

The "sliderValue * 13.2877 * 1200" thing is an input to the Detune parameter of the LPF.  Using 5Hz on the frequency parameter of a Web Audio Filter node:
* Slider value 0 = No detune (0 * 13.2877 * 1200 cents).
* Slider value 1 = 50000Hz (5Hz raised by 13.2877 octaves).

Will Pirkle has a really good book on implementing virtual synths.  Take a look at the PDF/files on [this page](http://www.willpirkle.com/virtual-analog-diode-ladder-filter/) to implement the Roland Diode-ladder filter.

I had a quick look at your code.  Looks like you might be trying to use the ScriptProcessorNode.  The new [AudoWorklet](https://developers.google.com/web/updates/2017/12/audio-worklet) might be a better choice.  I started messing around with it on Saturday (to emulate a Juno :)).

**Comment by pendragon-andyh** [comment]
My [analysis](https://github.com/pendragon-andyh/Juno60/tree/master/Filter/VCF) is missing because I didn't get that far.  One can infer a lot about the Juno's DCO/LFO/Chorus/ADSR by observing my project's wav files using something like Sonic Visualiser.  Will Pirkle's book padded-out my knowledge considerably.

The filters are super-difficult to analyse in this way.  When I get to that point on my project I am planning to wire-up my JU-06 and then do a series of "by ear" comparison tests.

**Comment by dzannotti** [comment]
@pendragon-andyh yep, i made a ticket to migrate to AudioWorklet (#2 ). 
Yeah the original ticket was indeed to plan to try to figure out the values from your wav files and a spectrometer indeed.
Would be great to collab on this, rather than write yet another juno emulator from scratch.

**Comment by pendragon-andyh** [comment]
I don't own a Juno (I got my recordings from a studio in Exeter when I was down there on holiday).  I do have a JU-06 (because I caught the Juno bug really bad!), but haven't got around to connecting it up.

There is a [page](http://www.synthmania.com/juno-60.htm) that contains recordings of Juno-60 patches.  Doesn't have all of the Bank B sounds.  The "Juno-60 Owner's Manual" PDF appears to have the slider settings for these patches on page 25.  Combining these means that you should be able to compare your project's accuracy yourself.  There are also some nice videos on YouTube that may help.

Note: I am won't be online much until next weekend.

**Comment by pendragon-andyh** [comment]
I have written-up some further notes on https://github.com/pendragon-andyh/junox/wiki/Notes---src-junox-lpf.js

**Comment by dzannotti** [comment]
@pendragon-andyh wow, that'll be super useful thanks!

**Comment by dzannotti** [comment]
closed by #17
