### ISSUE TITLE
Implement Pirkle LPF

### ISSUE THREAD

**Issue by dzannotti** [dzannotti/junox#15]
The LPF in Pirkle's book seems closer to the Juno's implementation

**Comment by pendragon-andyh** [comment]
When you do this then can you rename existing one to something like "vcf-moog.js" and use "vcf-diode-ladder.js" for the new version.  That will allow us to take a pick-and-mix approach to constructing other instruments.

I like the Moog filter because the maths for calculating the parameters are super easy. It would expect it to take me a couple of elapsed-weeks to work out good mappings for most other designs.

**Comment by pendragon-andyh** [comment]
I am hoping that the main difference between the implementations is the resonance.  With the resonance slider at 10, the actual cutoff frequency apparently `Fc` to `Fc * 0.707` (according to Pirkle's Synth book).  This is borne out by the calibration section of the Service Notes.
